apiVersion: v1
kind: Service
metadata:
  name: {{ include "async-long-request-proxy.fullname" . }}
  labels:
    {{- include "async-long-request-proxy.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.config.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "async-long-request-proxy.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: api
