{{- if not .Values.secret.existingSecret -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "async-long-request-proxy.fullname" . }}
  labels:
    {{- include "async-long-request-proxy.labels" . | nindent 4 }}
type: Opaque
data:
  DATABASE_URL: {{ tpl .Values.secret.databaseUrl . | b64enc | quote }}
  REDIS_HOST: {{ tpl .Values.secret.redisHost . | b64enc | quote }}
  REDIS_PORT: {{ tpl .Values.secret.redisPort . | b64enc | quote }}
  REDIS_PASSWORD: {{ .Values.secret.redisPassword | default "" | b64enc | quote }}
  PROXY_API_KEY: {{ .Values.secret.proxyApiKey | default "" | b64enc | quote }}
{{- end -}}
